server:
  port: 5005

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 3
      max-lifetime: 30000
      connection-timeout: 40000
      pool-name: PostgreSQL
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false



